import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--theme-ui-colors-background)',
        canvas: 'var(--theme-ui-colors-canvas)',
        muted: 'var(--theme-ui-colors-muted)',
        offer: 'var(--theme-ui-colors-offer)',
        navbar: 'var(--theme-ui-colors-navbar)',
        card: 'var(--theme-ui-colors-card)',
        tertiary: 'var(--theme-ui-colors-tertiary)',
        accent: 'var(--theme-ui-colors-accent)',
        tooltip: 'var(--theme-ui-colors-tooltip)',
        border: 'var(--theme-ui-colors-border)',
        separator: 'var(--theme-ui-colors-separator)',
        text: 'var(--theme-ui-colors-text)',
        textOnDark: 'var(--theme-ui-colors-textOnDark)',
        tertiaryText: 'var(--theme-ui-colors-tertiaryText)',
        tertiaryTextOnDark: 'var(--theme-ui-colors-tertiaryTextOnDark)',
        accentText: 'var(--theme-ui-colors-accentText)',
        accentTextOnDark: 'var(--theme-ui-colors-accentTextOnDark)',
        whisper: 'var(--theme-ui-colors-whisper)',
        primary: 'var(--theme-ui-colors-primary)',
        primaryOnDark: 'var(--theme-ui-colors-primaryOnDark)',
        secondary: 'var(--theme-ui-colors-secondary)',
        danger: 'var(--theme-ui-colors-danger)',
        like: 'var(--theme-ui-colors-like)',
        neutral: 'var(--theme-ui-colors-neutral)',
        rating: 'var(--theme-ui-colors-rating)',
        focused: 'var(--theme-ui-colors-focused)',
        disabled: 'var(--theme-ui-colors-disabled)',
        info: 'var(--theme-ui-colors-info)',
        error: 'var(--theme-ui-colors-error)',
        success: 'var(--theme-ui-colors-success)',
        warning: 'var(--theme-ui-colors-warning)',
        easy: 'var(--theme-ui-colors-easy)',
        moderate: 'var(--theme-ui-colors-moderate)',
        difficult: 'var(--theme-ui-colors-difficult)',
        tour: 'var(--theme-ui-colors-tour)',
        highlight: 'var(--theme-ui-colors-highlight)',
        pioneer: 'var(--theme-ui-colors-pioneer)',
        expert: 'var(--theme-ui-colors-expert)',
        facebook: 'var(--theme-ui-colors-facebook)',
        apple: 'var(--theme-ui-colors-apple)',
      }
    },
  },
  plugins: [],
}
export default config
